# Generated by Django 5.0.3 on 2024-04-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_client_user_mailingsettings_user_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('change_status', 'Может отключать рассылку')], 'verbose_name': 'настройки рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
    ]
